create schema api;

create table api.blog (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  published boolean not null default false,
  created_at timestamptz not null default now()
);

insert into api.blog (title, body, published)
values
  ('first post', 'hello world', true),
  ('draft post', 'not published yet', false);

create role anon noinherit;
create role authenticated noinherit;

grant usage on schema api to anon, authenticated;

grant select on api.blog to anon;

grant select, insert, update, delete on api.blog to authenticated;

create role authenticator noinherit login password 'mysecretpassword';

grant anon to authenticator;
grant authenticated to authenticator;
